authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'authentication'

urlpatterns = [
    path(r'login/', views.loginView, name='login'),
    path(r'register/', views.registerView, name='register'),
    path(r'logout/', views.logoutView, name='logout'),

]

director/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'director'
urlpatterns = [
    path('', views.AdminDashboardView.as_view(), name='index'),
    # Camera
    path('cameraList/', views.AdminCameraListView.as_view(), name='cameraList'),
    path('cameraDetail/<pk>', views.cameraDetailView, name='cameraDetail'),
    path('addCamera/', views.AdminAddCameraView, name='addCamera'),
    # Detection
    path('detectionList/', views.AdminDetectionListView.as_view(), name='detectionList'),
    path('detectionDetail/<str:det_id>/', views.detectionDetailView, name='detectionDetail'),
    # Settings

]

authentication/forms.py
from django import forms
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput)
    username = forms.CharField(widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

authentication/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import LoginForm, UserRegistrationForm
from django.conf import settings
from django.core.files.storage import FileSystemStorage

auth = settings.FIREBASE_AUTH
db = settings.FIRESTORE_DB
# Create your views here.
def loginView(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('director:index')
                else:
                    return render(request, 'authentication/login.html',
                                  {'error_message': 'Disabled account', 'form': form})
            else:
                return render(request, 'authentication/login.html', {'error_message': 'Invalid login', 'form': form})
    else:
        form = LoginForm()
    return render(request, 'authentication/login.html', {'form': form})


def registerView(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data["password"]
            online_user = auth.create_user(email=email, password=password)
            data = {"email": email, "username": username, "password": password, "user_id": online_user.uid}
            db.collection("Users").document(online_user.uid).set(data)

            return render(request, 'authentication/register_done.html', {'new_user': new_user})
    else:
        form = UserRegistrationForm()
    return render(request, 'authentication/register.html', {'form': form})


@login_required
def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('inspector:index'))

authentication/templates/authentication/authBase.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title%}
      {% endblock %}

    <link rel="shortcut icon" href="{% static 'director/assets/images/logo.png' %}" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'auth/fonts/material-design-iconic-font.min.css'%}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'auth/css/style.css'%}">
</head>
<body>
    <div class="main">
      {% block content%}


      {% endblock %}
    </div>

    <!-- JS -->
    <script src="{% static 'auth/js/jquery.min.js'%}"></script>
    <script src="{% static 'auth/js/main.js'%}"></script>
</body>
</html>

authentication/templates/authentication/login.html
{% extends 'authentication/authBase.html' %}
{%load static%}
{% load widget_tweaks %}
{% block title%}
    <title>Sign In Form</title>
{% endblock %}
{% block content%}
<!-- Sing in  Form -->
<section class="sign-in">
    <div class="container">
        {% if error_message %}
           <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <strong>Hey!</strong> Error occurred during processing.
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        <div class="signin-content">
            <div class="signin-image">
                <figure><img src="{% static 'auth/images/signin-image.jpg'%}" alt="sing up image"></figure>
                <a href="{%url 'authentication:register'%}" class="signup-image-link">Create an account</a>
            </div>

            <div class="signin-form">
                <h2 class="form-title">Sign up</h2>
                <form method="POST" class="register-form" id="login-form">
                     {% csrf_token %}


                    <div class="form-group">
                        <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {% render_field form.username   id="your_name" placeholder="Username"  %}

                    </div>
                    <div class="form-group">
                        <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                        {% render_field form.password id="your_pass"  placeholder="Password" %}
                    </div>
                    <div class="form-group">
                        <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                        <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                    </div>
                    <div class="form-group form-button">
                        <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                    </div>
                </form>
                <div class="social-login">
                    <span class="social-label">Or login with</span>
                    <ul class="socials">
                        <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                        <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                        <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

authentication/templates/authentication/register.html
{% extends 'authentication/authBase.html' %}
{%load static%}
{% load widget_tweaks %}
{% block title%}
    <title>Sign Up Form </title>
{% endblock %}
{% block content%}
<!-- Sign up form -->
<section class="signup">
    <div class="container">
        {% if error_message %}
           <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <strong>Holy guacamole!</strong> You should check in on some of those fields below.
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        <div class="signup-content">
            <div class="signup-form">
                <h2 class="form-title">Sign up</h2>
                <form method="POST" class="register-form" id="register-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="email"><i class="zmdi zmdi-email material-icons-name"></i></label>
                        {% render_field form.email|attr:'required:true'  id="email" name="email" placeholder="Email" type="email" %}

                    </div>
                    <div class="form-group">
                        <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {% render_field form.username|attr:'required:true'  id="username" name="username" placeholder="Username" %}
                    </div>
                    <div class="form-group">
                        <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                        {% render_field form.password|attr:'required:true' id="pass" name="pass"  placeholder="Password" %}
                    </div>
                    <div class="form-group">
                        <label for="re_pass"><i class="zmdi zmdi-lock-outline"></i></label>
                        {% render_field form.password2|attr:'required:true' id="re_pass" name="re_pass"  placeholder="Repeat your password" %}
                    </div>
<!--                    <div class="form-group">-->
<!--                        <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />-->
<!--                        <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>-->
<!--                    </div>-->
                    <div class="form-group form-button">
                        <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                    </div>
                </form>
            </div>
            <div class="signup-image">
                <figure><img src="{% static 'auth/images/signup-image.jpg'%}" alt="sing up image"></figure>
                <a href="{%url 'authentication:login'%}" class="signup-image-link">I am already member</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

authentication/templates/authentication/register_done.html
{% extends 'authentication/authBase.html' %}
{%load static%}
{% load widget_tweaks %}
{% block title%}
    <title>Account created</title>
{% endblock %}
{% block content%}
<!-- Sign up form -->
<section class="signup">
    <div class="container">
        <div class="signup-content">
            <div class="signup-form">
                <br>
                <br>
                <br>
                <h4 align="center" class="form-title">Welcome {{ new_user.username|title }}!</h4>
                <p align="center">Your account has been successfully created. Now you can <a href="{% url 'authentication:login' %}">Login</a>.</p>
            </div>
            <div class="signup-image">
                <figure><img src="{% static 'auth/images/register_done.png'%}" width="210%" alt="sing up image"></figure>
            </div>
        </div>
    </div>
</section>
{% endblock %}