authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'authentication'

urlpatterns = [
    path(r'login/', views.loginView, name='login'),
    path(r'register/', views.registerView, name='register'),
    path(r'logout/', views.logoutView, name='logout'),

]

director/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'director'
urlpatterns = [
    path('', views.AdminDashboardView.as_view(), name='index'),
    # Camera
    path('cameraList/', views.AdminCameraListView.as_view(), name='cameraList'),
    path('cameraDetail/<pk>', views.cameraDetailView, name='cameraDetail'),
    path('addCamera/', views.AdminAddCameraView, name='addCamera'),
    # Detection
    path('detectionList/', views.AdminDetectionListView.as_view(), name='detectionList'),
    path('detectionDetail/<str:det_id>/', views.detectionDetailView, name='detectionDetail'),
    # Settings

]

director/models.py
import os

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from location_field.models.plain import PlainLocationField
import validators
from django.utils.translation import gettext_lazy as _


# Create your models here.
def validate_url(value):
    if not validators.url(value):
        raise ValidationError(_("%(value)s is not an even number"), params={"value": value}, )


class CameraModel(models.Model):
    camera_name = models.CharField(max_length=50, unique=True)
    city = models.CharField(max_length=20)
    location = PlainLocationField(based_fields=['city'], zoom=10)
    web_address = models.CharField(max_length=100, unique=False, validators=[validate_url])
    added_date = models.DateTimeField(auto_now_add=True)

    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.camera_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.web_address)
        super().save(*args, **kwargs)


class DetectionModel(models.Model):
    detected_time = models.DateTimeField()
    image_url = models.CharField(max_length=1000, validators=[validate_url])
    accuracy = models.IntegerField(max_length=1)
    camera_id = models.ForeignKey(CameraModel, on_delete=models.CASCADE)
    offline_user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.camera_id.camera_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.camera_id.camera_name + self.detected_time)
        super().save(*args, **kwargs)

director/forms.py
from django import forms
from location_field.forms.plain import PlainLocationField

from .models import CameraModel


class CameraForm(forms.ModelForm):
    camera_name = forms.CharField(max_length=50, required=True)
    web_address = forms.CharField(max_length=100, required=True)
    city = forms.CharField(max_length=40, required=True)
    location = PlainLocationField(based_fields=['city'],
                                  initial='41.311081,69.240562', zoom=10, required=True)

    class Meta:
        model = CameraModel
        fields = ['camera_name', 'web_address', 'city', 'location']

    def __init__(self, *args, **kwargs):
        super(CameraForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

director/views.py
import threading
import time
from datetime import datetime, timedelta

import pytz
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView
from google.cloud.firestore_v1 import FieldFilter


from .forms import CameraForm
from .models import CameraModel

db = settings.FIRESTORE_DB
camera_db = db.collection("Cameras")
detected_db = db.collection("Detected")
user_db = db.collection("Users")
storage = settings.FIREBASE_BUCKET
camera_names, detected_time_list, offline_user_ids, detection_ids = [], [], [], []
# Create an Event for notifying main thread.
delete_done = threading.Event()


def on_snapshot(col_snapshot, changes, read_time):
    for change in changes:
        dict_doc = change.document.to_dict()
        if dict_doc["accuracy"] == 0 and dict_doc["detected_time"] not in detected_time_list:
            if change.type.name == "ADDED":
                detected_time_list.append(dict_doc["detected_time"])
                detection_ids.append(change.document.id)
                camera_names.append(dict_doc["camera_name"])
                offline_user_ids.append(dict_doc["offline_user_id"])
            elif change.type.name == "MODIFIED":
                if dict_doc["accuracy"] != 0:
                    detected_time_list.remove(dict_doc["detected_time"])
                    camera_names.remove(dict_doc["camera_name"])
                    detection_ids.remove(change.document.id)
                    offline_user_ids.remove(dict_doc["offline_user_id"])
            elif change.type.name == "REMOVED":
                detected_time_list.remove(dict_doc["detected_time"])
                camera_names.remove(dict_doc["camera_name"])
                detection_ids.remove(change.document.id)
                offline_user_ids.remove(dict_doc["offline_user_id"])
                delete_done.set()


class AdminDashboardView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'director/index.html'

    def get_context_data(self, **kwargs):
        context = super(AdminDashboardView, self).get_context_data(**kwargs)

        return context


class AdminCameraListView(LoginRequiredMixin, ListView):
    template_name = 'director/camera_list.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super(AdminCameraListView, self).get_context_data(**kwargs)
        user = self.request.user

        return context


class AdminDetectionListView(LoginRequiredMixin, ListView):
    template_name = 'director/detection_list.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super(AdminDetectionListView, self).get_context_data(**kwargs)
        user = self.request.user
        try:
            col_query = detected_db.where(filter=FieldFilter("offline_user_id", "==", user.id))
            query_watch = col_query.on_snapshot(on_snapshot)
            context['length_notification'] = len(camera_names)
            context['detection'] = zip(detected_time_list, camera_names, detection_ids)
            det_list = detected_db.where(filter=FieldFilter("offline_user_id", "==", user.id)).stream()
            det_id, acc, cam_name, cap_img, det_img, det_time = [], [], [], [], [], []
            for doc in det_list:
                dict_doc = doc.to_dict()
                det_id.append(doc.id)
                acc.append(dict_doc["accuracy"])
                cam_name.append(dict_doc["camera_name"])
                cap_img.append(dict_doc["captured_image_url"])
                det_img.append(dict_doc["detected_image_url"])
                det_time.append(dict_doc["detected_time"])
                context['detection_list'] = zip(det_id, acc, cam_name, cap_img, det_img, det_time)
        except ObjectDoesNotExist:
            context["fill_the_requirements"] = True
        return context


@login_required
def AdminAddCameraView(request):
    try:
        user = request.user
        col_query = db.collection("Detected").where(filter=FieldFilter("offline_user_id", "==", user.id))
        query_watch = col_query.on_snapshot(on_snapshot)

        registered = False
        if request.method == "POST":
            user_doc = user_db.document(request.user.first_name)
            form = CameraForm(data=request.POST)
            if form.is_valid():
                c_form = form.save(commit=False)
                data = {
                    'camera_name': form.cleaned_data['camera_name'],
                    'city': form.cleaned_data['city'],
                    'location': form.cleaned_data['location'],
                    'web_address': form.cleaned_data['web_address'],
                    'added_date': datetime.now(pytz.timezone('Asia/Tashkent')),
                    'user_offline_id': request.user.id,
                    'user_online_id': user_doc.id,
                }
                camera_db.add(data)
                c_form.user_id = request.user
                c_form.save()
                registered = True
        else:
            form = CameraForm()
        context = {'form': form, "registered": registered,
                   "length_notification": len(camera_names),
                   "detection": zip(detected_time_list, camera_names, detection_ids)
                   }
    except ObjectDoesNotExist:
        context = {'fill_the_requirements': True}
    return render(request, "director/add_camera.html", context)




@login_required
def cameraDetailView(request, pk):
    user = request.user
    col_query = db.collection("Detected").where(filter=FieldFilter("offline_user_id", "==", user.id))
    query_watch = col_query.on_snapshot(on_snapshot)
    key = settings.GOOGLE_API_KEY
    camera = get_object_or_404(CameraModel, pk=pk)
    lat1 = float(camera.location.split(",")[0])
    lon1 = float(camera.location.split(",")[1])

    user_lat1 = float(user.location.split(",")[0])
    user_lon1 = float(user.location.split(",")[1])
    form = CameraForm(request.POST or None, instance=camera)
    if request.user.is_active:
        if request.method == 'POST':
            if 'camera_update_btn' in request.POST:
                if form.is_valid():
                    form.save()
            elif 'camera_delete_btn' in request.POST:
                camera.delete()
                return redirect('director:index')
            return redirect('director:cameraDetail', pk=camera.pk)
    context = {
        "latitude1": lat1,
        "longitude1": lon1,

        "user_latitude1": user_lat1,
        "user_longitude1": user_lon1,
        "length_notification": len(camera_names),
        "detection": zip(detected_time_list, camera_names, detection_ids),
        'camera': camera,
        'form': form,
        'key': key,
    }
    return render(request, 'director/camera_detail.html', context)


@login_required
def detectionDetailView(request, det_id):
    user = request.user
    col_query = db.collection("Detected").where(filter=FieldFilter("offline_user_id", "==", user.id))
    query_watch = col_query.on_snapshot(on_snapshot)
    doc_ref = db.collection("Detected").document(det_id).get()
    dict_ref = doc_ref.to_dict()

    key = settings.GOOGLE_API_KEY
    # camera = get_object_or_404(CameraModel, camera_name=dict_ref["camera_name"])[0]
    camera = CameraModel.objects.get(camera_name=dict_ref["camera_name"])
    detected_time = dict_ref["detected_time"]
    captured_image_url = dict_ref["captured_image_url"]
    detected_image_url = dict_ref["detected_image_url"]
    detected_classes = dict_ref["detected_classes"]
    detected_accuracy = dict_ref["accuracy"]
    lat1 = float(camera.location.split(",")[0])
    lon1 = float(camera.location.split(",")[1])

    user_lat1 = float(user.location.split(",")[0])
    user_lon1 = float(user.location.split(",")[1])
    form = CameraForm(request.POST or None, instance=camera)
    if request.user.is_active:
        if request.method == 'POST':
            if 'true_positive_btn' in request.POST:
                db.collection("Detected").document(det_id).update({"accuracy": 1})
            elif 'false_positive_btn' in request.POST:
                db.collection("Detected").document(det_id).update({"accuracy": -1})
            return redirect('director:detectionList')
    context = {
        "latitude1": lat1,
        "longitude1": lon1,
        'detected_accuracy': detected_accuracy,
        "user_latitude1": user_lat1,
        "user_longitude1": user_lon1,
        "length_notification": len(camera_names),
        "detection": zip(detected_time_list, camera_names, detection_ids),
        'camera': camera,
        'form': form,
        'key': key,
        "detected_time": detected_time,
        "captured_image_url": captured_image_url,
        "detected_image_url": detected_image_url,
        "detected_classes": detected_classes,
    }
    return render(request, 'director/detection_detail.html', context)

director/templates/director/add_camera.html
<!-- SELECT2 EXAMPLE -->
{% extends 'director/base.html' %}
{% load static %}
{% block content %}
{{form.media}}
<div class="content-wrapper">

        <div class="row">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'director:index'%}">Dashboard</a></li>
                <li class="breadcrumb-item active">Add new camera</li>
              </ol>
            </nav>
            {% if fill_the_requirements %}
            <div class="card text-center">
                <div class="card-header">
                    *****************
                </div>
                <div class="card-body">
                  <h5 class="card-title">Attention!</h5>
                  <p class="card-text">Before you start you must fill your data.</p>
                  <a href="{% url 'director:profileSetting' %}" class="btn btn-outline-info btn-fw"><i class="mdi mdi-account-key" aria-hidden="true"></i> Update data</a>
                  <a href="{% url 'authentication:logout' %}" class="btn btn-outline-danger btn-fw"><i class=" mdi mdi-exit-to-app" aria-hidden="true"></i>Logout</a>
                </div>
                <div class="card-footer text-muted">
                  *****************
                </div>
              </div>
            {% else %}
                {% if registered %}
                <div class="card text-center">
                    <div class="card-header">
                        *****************
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">New Camera added!</h5>
                      <p class="card-text">New Camera successfully added. You can add more or go dashboard.</p>
                      <a href="{% url 'director:addCamera' %}" class="btn btn-outline-success btn-fw"><i class="mdi mdi-camera-enhance" aria-hidden="true"></i> Add new camera</a>
                      <a href="{% url 'director:index' %}" class="btn btn-outline-info btn-fw"><i class=" mdi mdi-exit-to-app" aria-hidden="true"></i> Go back to Main Page</a>
                    </div>
                    <div class="card-footer text-muted">
                      *****************
                    </div>
                  </div>
                {% else %}

                <div class="col-12 grid-margin">
                    <h2 class="text-center" >Section to add a new camera</h2>
                    <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Fill the form</h4>
                        <form class="form-sample" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                          {{form.media}}


                        <div class="btn-group mt-4" role="group" aria-label="Basic example">
                            <button type="submit" class="btn btn-info ">&nbsp &nbsp  Save  &nbsp &nbsp </button>
                            <button type="button" class="btn btn-warning "> Cancel</button>
                        </div>
                        </form>
                    </div>
                    </div>
                </div>
                {% endif %}
            {% endif %}
    </div>
</div>
{% endblock %}

<!-- /.card -->

director/templates/director/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    {{form.media}}
    <!-- Required meta tags -->
    <meta charset="utf-8" /><!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>{% block title %}Welcome, {{ user.username|title }}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/6.5.95/css/materialdesignicons.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/4.1.5/css/flag-icons.min.css" />
    <link rel="stylesheet" href="{% static 'director/assets/vendors/css/vendor.bundle.base.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/fontawesome.min.css" />
    <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'director/assets/css/style.css' %}" />
    <link rel="shortcut icon" href="{% static 'inspector/assets/img/logo/logo_mini.png' %}" />
        {% block style%}

        {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </head>
  <body>
    <div class="container-scroller">
      <!-- MENU -->
      <nav class="sidebar sidebar-offcanvas fixed-left  " id="sidebar">
        <div class="text-center sidebar-brand-wrapper d-flex align-items-center">
          <a class="sidebar-brand brand-logo" href="{% url 'director:index'  %}"><img src="{%static 'inspector/assets/img/logo/logo1.png'%}" alt="logo" /></a>
          <a class="sidebar-brand brand-logo-mini pl-4 pt-3" href="{% url 'director:index'  %}"><img src="{% static 'inspector/assets/img/logo/logo_mini.png' %}" alt="logo" /></a>
        </div>
        <ul class="nav">
          <li class="nav-item nav-profile">
            <a href="{% url 'director:index'  %}" class="nav-link">
              <div class="nav-profile-text d-flex flex-column pr-3">
                <span class="font-weight-medium mb-2">{{user.username}}</span>
              </div>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'director:index'  %}">
              <i class="mdi mdi-home-map-marker menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'director:cameraList' %}">
              <i class="mdi mdi-table-edit menu-icon"></i>
              <span class="menu-title">Your resume</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'director:cameraList' %}">
              <i class="mdi mdi-cloud-upload menu-icon"></i>
              <span class="menu-title">Upload Your Resume</span>
            </a>
          </li>

          <li class="nav-item sidebar-actions">
            <div class="nav-link">
              <div class="mt-4">

                <ul class="mt-4 pl-0">

                  <li><a class="nav-link" href="{% url 'authentication:logout'  %}">
                    <i class="mdi mdi-exit-to-app menu-icon"></i>
                    <span class="menu-title">Logout</span>
                  </a></li>

                </ul>
              </div>
            </div>
          </li>
        </ul>
      </nav>
      <div class="container-fluid page-body-wrapper">

        <!-- THEME SETTING -->
        <div id="theme-settings" class="settings-panel">
          <i class="settings-close mdi mdi-close"></i>
          <p class="settings-heading">SIDEBAR SKINS</p>
          <div class="sidebar-bg-options selected" id="sidebar-default-theme">
            <div class="img-ss rounded-circle bg-light border mr-3"></div> Default
          </div>
          <div class="sidebar-bg-options" id="sidebar-dark-theme">
            <div class="img-ss rounded-circle bg-dark border mr-3"></div> Dark
          </div>
          <p class="settings-heading mt-2">HEADER SKINS</p>
          <div class="color-tiles mx-0 px-4">
            <div class="tiles light"></div>
            <div class="tiles dark"></div>
          </div>
        </div>

        <nav class="navbar col-lg-12 col-12 p-lg-0 fixed-top d-flex flex-row">
          <div class="navbar-menu-wrapper d-flex align-items-stretch justify-content-between">
            <a class="navbar-brand brand-logo-mini align-self-center d-lg-none" href="{% url 'director:index'  %}"><img src="{% static 'inspector/assets/img/logo/logo_mini.png' %}" alt="logo" width="10%" /></a>
            <button class="navbar-toggler navbar-toggler align-self-center mr-2" type="button" data-toggle="minimize">
              <i class="mdi mdi-menu"></i>
            </button>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                 <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                  <i class="mdi mdi-bell-outline"></i>
                  <span class="count count-varient1">{{length_notification}}</span>
                </a>
                <div class="dropdown-menu navbar-dropdown navbar-dropdown-large preview-list" aria-labelledby="notificationDropdown">
                  <h6 class="p-3 mb-0">Notifications</h6>
                  {% for d_t, c_n, d_i in detection %}
                  <a class="dropdown-item preview-item" href="{% url 'director:detectionDetail' det_id=d_i %} ">
                    <div class="preview-item-content">
                      <p class="mb-0"> {{c_n}} detected danger at {{d_t|date:'H:i:s d-m-y'}}
                      </p>
                    </div>
                  </a>
                  {%endfor%}
                  <div class="dropdown-divider"></div>
                  <br>
                </div>
              </li>

              <li class="nav-item nav-search border-0 ml-1 ml-md-3 ml-lg-5 d-none d-md-flex">
                <form class="nav-link form-inline mt-2 mt-md-0">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" />
                   <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-magnify"></i>
                      </span>
                    </div>
                  </div>
                </form>
              </li>
            </ul>
            <ul class="navbar-nav navbar-nav-right ml-lg-auto">

              <li class="nav-item nav-profile dropdown border-0">
                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown">
                  <i class="mdi mdi mdi-account-circle mr-2 text-success"></i>
                  <span class="profile-name">  {{user.username|title}}</span>
                </a>
                <div class="dropdown-menu navbar-dropdown w-100" aria-labelledby="profileDropdown">
                  <a class="dropdown-item" href=""><i class="mdi  mdi-account-key mr-2 text-primary"></i>Setting</a>
                  <a class="dropdown-item" href="{% url 'authentication:logout' %}"><i class="mdi mdi-logout mr-2 text-primary"></i> Logout </a>
                </div>
              </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
              <span class="mdi mdi-menu"></span>
            </button>
          </div>
        </nav>
        <div class="main-panel">
        {% block content%}

        {% endblock %}
        <br>
        <br>
        <br>
        <footer class="footer fixed-bottom  d-flex flex-row">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-center d-sm-inline-block">Copyright ©  Job Recommendation System  {{date}}</span>
           </div>
        </footer>
      </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'director/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    {% block scripts %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


    <script src="{% static 'director/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'director/assets/vendors/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'director/assets/vendors/flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'director/assets/vendors/flot/jquery.flot.categories.js' %}"></script>
    <script src="{% static 'director/assets/vendors/flot/jquery.flot.fillbetween.js' %}"></script>
    <script src="{% static 'director/assets/vendors/flot/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'director/assets/vendors/flot/jquery.flot.pie.js' %}"></script>
        {% block script%}

        {% endblock %}
    <script src="{% static 'director/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'director/assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'director/assets/js/misc.js' %}"></script>
    <script src="{% static 'director/assets/js/chart.js' %}"></script>
    <script src="{% static 'director/assets/js/chart-area-demo.js' %}"></script>

    <!-- endinject -->
    <!-- Custom js for this page -->

    <!-- End custom js for this page -->
  </body>
</html>

director/templates/director/profile_update.html
<!-- SELECT2 EXAMPLE -->
{% extends 'director/base.html' %}
{% load static %}
{% block content %}
{{form.media}}
<div class="content-wrapper">

        <div class="row">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'director:index'%}">Dashboard</a></li>
                <li class="breadcrumb-item active">Profile Update</li>
              </ol>
            </nav>
            {% if fill_the_requirements %}
            <div class="card text-center">
                <div class="card-header">
                    *****************
                </div>
                <div class="card-body">
                  <h5 class="card-title">Attention!</h5>
                  <p class="card-text">Before you start you must fill your data.</p>
                  <a href="{% url 'director:profileSetting' %}" class="btn btn-outline-info btn-fw"><i class="mdi mdi-account-key" aria-hidden="true"></i> Update data</a>
                  <a href="{% url 'authentication:logout' %}" class="btn btn-outline-danger btn-fw"><i class=" mdi mdi-exit-to-app" aria-hidden="true"></i>Logout</a>
                </div>
                <div class="card-footer text-muted">
                  *****************
                </div>
              </div>
            {% else %}
                {% if registered %}
                <div class="card text-center">
                    <div class="card-header">
                        *****************
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">Congratulations!</h5>
                      <p class="card-text">Your data successfully updated.</p>
                      <a href="{% url 'director:profileUpdate' %}" class="btn btn-outline-success btn-fw"><i class="mdi mdi-account-key" aria-hidden="true"></i> Update again</a>
                      <a href="{% url 'director:index' %}" class="btn btn-outline-info btn-fw"><i class=" mdi mdi-exit-to-app" aria-hidden="true"></i> Go back to Main Page</a>
                    </div>
                    <div class="card-footer text-muted">
                      *****************
                    </div>
                  </div>
                {% else %}

                <div class="col-12 grid-margin">
                    <h2 class="text-center" >Section to update your data</h2>
                    <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Fill the form</h4>
                        <form class="form-sample" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                          {{form.media}}
                            {{ form }}


                        <div class="btn-group mt-4" role="group" aria-label="Basic example">
                            <button type="submit" class="btn btn-info ">&nbsp &nbsp  Save  &nbsp &nbsp </button>
                            <button type="button" class="btn btn-warning "> Cancel</button>
                        </div>
                        </form>
                    </div>
                    </div>
                </div>
                {% endif %}
            {% endif %}
    </div>
</div>
{% endblock %}

<!-- /.card -->